### ISSUE TITLE
get_current_page_url returns localhost when the plugin is running inside a Docker image

### ISSUE THREAD

**Issue by YourAutisticLife** [wp-insider/simple-membership#108]
Versions
=======

WordPress: 6.4.3
Plugin: 4.4.2

Actual Behavior
============

After a successful login, the browser is redirected to a `localhost` address.

Desired Behavior
=============

The browser should be redirected to the actual site.

Observations
==========

I think the problem happens because my instance is running inside a Docker image.

The following code for `get_current_page_url` works. However, I don't know if I broke anything else:

```
        public static function get_current_page_url() {
                $pageURL = 'http';

        if ( isset( $_SERVER['SCRIPT_URI'] ) && ! empty( $_SERVER['SCRIPT_URI'] ) ) {
                        $pageURL = $_SERVER['SCRIPT_URI'];
            $pageURL = str_replace(':443', '', $pageURL);//remove any port number from the URL value (some hosts include the port number with this).
                        $pageURL = apply_filters( 'swpm_get_current_page_url_filter', $pageURL );
                        return $pageURL;
                }

                //Check if 'SERVER_NAME' is set. If not, try get the URL from WP.
                if( !isset( $_SERVER['SERVER_NAME'] ) ) {
                        global $wp;
                        if( is_object( $wp ) && isset( $wp->request ) ){
                                //Try to get the URL from WP
                                $pageURL = home_url( add_query_arg( array(), $wp->request ) );
                                $pageURL = apply_filters( 'swpm_get_current_page_url_filter', $pageURL );
                                return $pageURL;                                
                        }
                }

                $pageURL = '';
                $homeURL = home_url();
                if ( isset( $_SERVER['SERVER_PORT'] ) && ( $_SERVER['SERVER_PORT'] != '80' ) && ( $_SERVER['SERVER_PORT'] != '443' ) ) {
                        $pageURL .= ltrim( $homeURL, '.*' ) . ':' . $_SERVER['SERVER_PORT'] . $_SERVER['REQUEST_URI'];
                } else {
                        $pageURL .= ltrim( $homeURL, '.*' ) . $_SERVER['REQUEST_URI'];
                }

                //Clean any known port numbers from the URL (some hosts may include these port numbers).
                $pageURL = str_replace(':8080', '', $pageURL);

                //Trigger filter 
                $pageURL = apply_filters( 'swpm_get_current_page_url_filter', $pageURL );

                return $pageURL;
        }
```

**Comment by wp-insider** [comment]
Hi, I don't see this issue you mentioned on my site. What are the steps to reproduce the issue so I can see it in our test site?

**Comment by wp-insider** [comment]
Oh, you are talking about your localhost setup. Support for localhost setup is beyond the scope of our standard support. You are free use the plugin however you want to but localhost setup varies significantly based on many factors which we can't control. If you see any issue on a live server/site, we can will be able to investigate that in a systematic way.

**Comment by YourAutisticLife** [comment]
The server is here:

https://www.yourautisticlife.com

**Comment by wp-insider** [comment]
We use Linode.com to spin up an instance using a server configuration that we want to use to test a particular feature of the plugin.  

Can you give us any steps/instructions in terms of how we should setup a new server (using linode.com) so we can recreate the issue on this server? That will allow us to investigate this more in-depth.

**Comment by wp-insider** [comment]
**Sidenote:** Are you able to use the following filter hook to override the redirect URL on your site using a few lines of custom code?

swpm_get_current_page_url_filter

**Comment by YourAutisticLife** [comment]
I'm on linode.com myself. I'm using a Linode 4GB plan with the Debian 12 disk. I run WordPress in Docker.

Here's the `docker-compose.yml`:

```
version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      wordpressnet:
        ipv4_address: 10.10.11.3
    environment:
      MYSQL_ROOT_PASSWORD: fake_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: fake_password
    volumes:
      - ./db:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:fpm
    restart: always
    networks:
      wordpressnet:
        ipv4_address: 10.10.11.4
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: fake_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
  nginx:
    image: nginx:latest
    networks:
      wordpressnet:
        ipv4_address: 10.10.11.2
    expose:
        - 80
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./wordpress:/var/www/html
    restart: always

volumes:
  mysql:

networks:
  wordpressnet:
    external:
      name: wordpressnet
```

And the `default.conf` for `nginx`:

```
server { 
  listen 80; 
  server_name localhost; 
  root /var/www/html; 

  index index.php; 

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  rewrite /wp-admin$ $scheme://$host$uri/ permanent;

  location ~ [^/]\.php(/|$) { 
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    if (!-f $document_root$fastcgi_script_name) {
      return 404;
    }

    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO       $fastcgi_path_info;
    fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
    add_header X-FastCGI-Cache $upstream_cache_status;

    fastcgi_pass   10.10.11.4:9000;
    fastcgi_index  index.php; 
  } 
}
```

I haven't tried using `swpm_get_current_page_url_filter` yet.
